# -*- coding: utf-8 -*-
from pruebas import flujo basico1
import os
os.system( "python3 flujo_estandar/flujo_basico.py")
print("termine de preprocesar el flujo estandar")
os.system( "python3 flujo_estandar/entropiamaxima.py")
print("termine de analisar el flujo estandar")
os.system( "python3 Flujo_experimental_1/flujo_basico1.py")
print("termine de preprocesar el flujo experimental 1")
os.system( "python3 Flujo_experimental_1/entropiamaxima.py")
print("termine de analisar el flujo experimental 1")
os.system( "python3 Flujo_experimental_2/flujo_experimental2.py")
print("termine de preprocesar el flujo experimental 2")
os.system( "python3 Flujo_experimental_2/entropiamaxima.py")
print("termine de analisar el flujo experimental 2")
os.system( "python3 Flujo_experimental_3/flujo_experimental3.py")
print("termine de preprocesar el flujo experimental 3")
os.system( "python3 Flujo_experimental_3/entropiamaxima.py")
print("termine de analisar el flujo experimental 3")
os.system( "python3 texto_sin_preprocesar/textosolo.py")
print("termine de transformar el textosolo")
os.system( "python3 texto_sin_preprocesar/entropiamaxima.py")
print("termine de hacer todo")

#os.system("python archivo2.py")
#os.system("python archivo3.py")
#result=commands.getoutput('/pruebas/python3 entropiamaxima.py')